name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Intalling dependencies
        run: pnpm install --frozen-lockfile

      - name: Running lint
        run: pnpm lint
    
      - name: Running tests
        run: pnpm test